language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
install:
    - python bootstrap-buildout.py
    - bin/buildout
script:
    - bin/nosetests --with-coverage --cover-package=zLOG --cover-min-percentage=100%
notifications:
    email: false
